name: fpic_monitoring_tools
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  shared_preferences: ^2.3.2
  get: ^4.6.6
  loading_animation_widget: ^1.3.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0
  path: ^1.8.3
  timeago: ^3.7.0
  fl_chart: ^0.69.0
  url_launcher: ^6.3.1
  toastification: ^2.3.0
  webview_flutter: ^4.2.0
  khmer_fonts: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/fpic_monitoring_tools_v3.png"
  min_sdk_android: 26
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/fpic_monitoring_tools_v3.png"

flutter:
  uses-material-design: true
  # If you want to use a bundled Khmer font, add it under `assets/fonts/`
  # and uncomment the block below, then run `flutter pub get`.
  # fonts:
  #   - family: Khmer
  #     fonts:
  #       - asset: assets/fonts/KhmerOS.ttf
  assets:
    - assets/
